name: .NET CI Pipeline
#details
on:
  push:
  pull_request:
    branches: 
     - main
     - feature1
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/WebApp/WebApp.csproj

      - name: Build
        run: dotnet build --no-restore src/WebApp/WebApp.csproj

      - name: Test
        run: dotnet test --no-build tests/Webapp.tests/WebApp.Tests.csproj
<<<<<<< HEAD
        
      - name: Publish
        run: dotnet publish src/WebApp/WebApp.csproj -c Release -o publish
=======

              - name: Publish
        run: dotnet publish src/WebApp/WebApp.csproj -c Release -o publish

      - name: Upload publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp-publish
          path: publish/
>>>>>>> feature1
